### ISSUE TITLE
[NF0003] Implementar uma tab para conversão de ID

### ISSUE THREAD

**Issue by fcsest** [guarastats/GuaraDash#17]
# Implementar uma terceira tab para conversão de ID.
# Tasks:
- [ ] Atualizar os pacotes que serão utilizados
  - [ ] Atualizar o preenchimento do vetor declarado dentro da função ler_libs no arquivo `./app.R` com os novos pacotes que serão utilizados

- [ ] Tabela com IDs
  - [ ] Montar uma base com IDs aleatórios no `R`
  - [ ] Salvar essa base em `.csv` na pasta data

- [x] Interface
  - [x] Criar mais uma tab no arquivo `./components/sidebar.R`
  - [x] Criar a primeira box com os inputs abaixo no arquivo `./components/body.R`
    - [x] [Input para importar a base](https://shiny.rstudio.com/gallery/file-upload.html)
    - [x] [Input para trocar id A por B ou id B por A](http://shinyapps.dreamrs.fr/shinyWidgets/)
    - [x] [Input para trocar ID](http://shinyapps.dreamrs.fr/shinyWidgets/)
    - [x] [Input para exportar a base](https://shiny.rstudio.com/gallery/file-download.html)
  - [x] Criar a segunda box com a visualização da base no arquivo `./components/body.R`
    - [x] [Utilizar o package `DT`](https://rstudio.github.io/DT/)
    - [x] [`DTOutput` dentro da box 2](https://shiny.rstudio.com/articles/datatables.html)

- [ ] Server
  - [ ] [Importar base e os parâmetros quando selecionada](https://github.com/rstudio/shiny-examples/blob/master/009-upload/app.R)
  - [ ] [Criar o `DTOutput` para visualização da base](https://www.rdocumentation.org/packages/DT/versions/0.8/topics/dataTableOutput)
  - [ ] [Trocar ID quando clicado o botão](https://shiny.rstudio.com/gallery/actionbutton-demo.html)
    - [ ] [Criar uma função pra alterar os IDs](http://r-pkgs.had.co.nz/r.html)
    - [ ] Salvar a função em R na pasta `./functions/change_id.R`
    - [ ] Importar a função no arquivo `./app.R`
  - [ ] [Exportar no path destino](https://github.com/rstudio/shiny-examples/blob/master/010-download/app.R)

# Useful Links
Topic | Link
------------ | -------------
Intro R | [Intro R Workshop, cap 10](https://robwschlegel.github.io/Intro_R_Workshop/tidy.html)
Shiny App | [Shiny Mini Workshop](https://github.com/daattali/shiny-mini-workshop/blob/master/Shiny%20Mini%20Workshop%20-%20SER%202019.pdf)
Change ID | [Convertendo ID com `dplyr`](https://stackoverflow.com/questions/14417612/r-replace-an-id-value-with-a-name)
Data Manipulation | [Explicação das funções `join` do `dplyr`](https://www.rdocumentation.org/packages/dplyr/versions/0.7.8/topics/join)
Data Manipulation | [Explicação das funções `join` do `dplyr` em PT-BR](https://rpubs.com/CristianaFreitas/311735)
Shiny Dashboard | [Exemplo de um Shiny Dashboard](https://datascienceplus.com/building-a-simple-sales-revenue-dashboard-with-r-shiny-shinydashboard/)
Shiny Dashboard | [Exemplo de um Shiny Dashboard em PT-BR](https://lurodrigo.com/_posts/2018-03-05-shiny-dashboard-reatividade/)
Shiny with DT | [Utilizando o package DT no Shiny](https://rstudio.github.io/DT/shiny.html)
Shiny with DT | [Exemplo de aplicativo em Shiny utilizando DT (tem uma aba com o código utilizado)](https://beatriz-milz.shinyapps.io/pesquisa_periodicos/)
Shiny HTML Tags | [Glossário de tags HTML em Shiny](https://shiny.rstudio.com/articles/tag-glossary.html)
Awesome Packages for Shiny | [Pacotes impressionantes para utilizar no Shiny](https://github.com/nanxstats/awesome-shiny-extensions)
Shiny Tips | [Algumas dicas em Shiny](https://deanattali.com/blog/advanced-shiny-tips/)
